version: "3.8"
name: "vite_app"

services:
  app:
    image: vite_app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./nginx/nginx.conf://etc/nginx/nginx.conf:ro"
#     networks:
#       network:
#         ipv4_address: 3.10.0.64

# networks:
#   network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 3.10.0.0/16
#           gateway: 3.10.0.1
