version: "3"
services:
  app:
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
